# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('weixinOpenid', models.CharField(max_length=255, null=True)),
                ('submitTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('fromAddress', models.CharField(max_length=255)),
                ('toAddress', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
