# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='toAddress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='weixinOpenid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
