# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinpost', '0004_auto_20160619_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='status',
            new_name='statu',
        ),
    ]
