# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinpost', '0005_auto_20160619_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='statu',
        ),
    ]
