# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinpost', '0006_remove_orderinfo_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(blank=True, default='post', max_length=25),
        ),
    ]
