# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixinpost', '0007_orderinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='fromAddress',
            field=models.CharField(max_length=255, verbose_name='取件地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='phoneNumber',
            field=models.CharField(max_length=25, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='senderName',
            field=models.CharField(max_length=25, verbose_name='寄件人名称'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(blank=True, default='post', max_length=25, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='submitTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='toAddress',
            field=models.CharField(blank=True, max_length=255, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='weixinOpenid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信OPENID'),
        ),
    ]
